### ISSUE TITLE
Weapon Types

### ISSUE THREAD

**Issue by eroz33** [yaragg/Horde-War-Z#13]
- [x] High damage pistol - mid damage
- [x] Fast speed sniper - long reload, high damage
- [x] High fire rate smg - low damage
- [x] Shotgun - short range - high damage

**Comment by eroz33** [comment]
Variable damage has yet to be implemented, shotgun spread is working, but bullet range also needs added

**Comment by yaragg** [comment]
Bullet range could be done by adjusting the bullet speed and lifespan. For variable damage we can make Zombie's DecreaseHealth( ) take an argument, I don't think that breaks anything.
