### ISSUE TITLE
Art Asset Implementation

### ISSUE THREAD

**Issue by jarell4** [yaragg/Horde-War-Z#28]
Replacing the current placeholder objects with all of the completed sprite assets so far, and making any modifications to game scripts accordingly.

**Comment by eroz33** [comment]
Implemented Players and Weapons, and updated the necessary scripts to preserve functionality.

**Comment by eroz33** [comment]
- [x] Players
- [x] Weapons
- [ ] Zombies
- [ ] Tiles
- [ ] Misc Objects

**Comment by jarell4** [comment]
Are there any other zombie sprites besides the turned citizens? If not, was thinking we could have their colors be randomized a bit to add more variety, which wouldn't be too hard to implement either.

**Comment by yaragg** [comment]
I remember Claire drew some, like the dog zombie, but I don't know if she continued working on them or if it was just concept art. The ones we have here are the only ones I found in the branches. Randomizing the colors might be a good idea in this case yeah.

**Comment by eroz33** [comment]
Sounds good to me!
