### ISSUE TITLE
Health tracking

### ISSUE THREAD

**Issue by yaragg** [yaragg/Horde-War-Z#4]
In icons for now. Hearts? Brains?

**Comment by yaragg** [comment]
Do we display those for the zombies too or do we hide that information from the player?

**Comment by eroz33** [comment]
I think showing health for the zombies too would crowd the screen once we have more than just a few zombies. As for the actual icon, I'm cool with either.

**Comment by yaragg** [comment]
Fair point, I didn't think of that. Let's limit it to the player characters then. How many hearts/whatever should each character have? How many hits can the zombies take?

**Comment by eroz33** [comment]
I'm thinking 3-4 hits for a character, and maybe 2 for the zombies?

**Comment by jarell4** [comment]
Sounds good to me. 4 hits for the player, 2 for the zombies
